name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version: ['3.x']
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    
    - name: Install system dependencies (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk
    
    - name: Build with PyInstaller
      run: |
        # Increase recursion limit for complex dependency trees
        python -c "import sys; sys.setrecursionlimit(sys.getrecursionlimit() * 5)"
        pyinstaller --clean -y --distpath ./dist --workpath ./build FittingApp.spec

    - name: Zip artifact (Windows)
      if: runner.os == 'Windows'
      run: |
        Compress-Archive -Path 'dist\*' -DestinationPath "${{ matrix.os }}-executable.zip"
      shell: pwsh
  
    - name: Zip artifact (Unix)
      if: runner.os != 'Windows'
      run: |
        cd dist
        zip -r ../${{ matrix.os }}-executable.zip ./*

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-executable
        path: ./${{ matrix.os }}-executable.zip

  publish_release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./artifacts

    - name: Create release in the public repo
      uses: softprops/action-gh-release@v2
      with:
        repository: ahmadomira/fitting-app-releases
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        files: ./artifacts/**/*.zip
        token: ${{ secrets.RELEASE_REPO_TOKEN }}
